# ruff: noqa: E501
"""initial core schema

Revision ID: 0001
Revises:
Create Date: 2026-07-27 17:30:10.815707+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_catalogs",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "dimension > 0", name=op.f("ck_feature_catalogs_feature_catalog_positive_dimension")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_catalogs")),
        sa.UniqueConstraint("checksum", name="feature_catalog_checksum"),
        sa.UniqueConstraint("name", "version", name="feature_catalog_name_version"),
    )
    op.create_table(
        "organizations",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "retention_policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(slug) > 0", name=op.f("ck_organizations_organization_slug_nonempty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name="organization_slug"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=240), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=120), nullable=False),
        sa.Column("entity_id", sa.String(length=160), nullable=False),
        sa.Column("request_id", sa.String(length=160), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "details_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        sa.UniqueConstraint("event_hash", name="audit_event_hash"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_logs_entity_time", ["entity_type", "entity_id", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_audit_logs_request", ["request_id"], unique=False)

    op.create_table(
        "feature_definitions",
        sa.Column("catalog_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=False),
        sa.Column("value_kind", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "constraints_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "ordinal > 0", name=op.f("ck_feature_definitions_feature_positive_ordinal")
        ),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["feature_catalogs.id"],
            name=op.f("fk_feature_definitions_catalog_id_feature_catalogs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_definitions")),
        sa.UniqueConstraint("catalog_id", "code", name="feature_code_per_catalog"),
        sa.UniqueConstraint("catalog_id", "ordinal", name="feature_ordinal_per_catalog"),
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "logon",
                "device",
                "file",
                "http",
                "email",
                "ldap",
                name="ingest_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="job_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("input_uri", sa.String(length=1024), nullable=False),
        sa.Column("original_filename", sa.String(length=300), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.String(length=80), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("processed_rows", sa.Integer(), nullable=False),
        sa.Column("rejected_rows", sa.Integer(), nullable=False),
        sa.Column("min_event_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_event_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "progress_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "total_rows >= 0 AND processed_rows >= 0 AND rejected_rows >= 0",
            name=op.f("ck_ingestion_jobs_ingestion_nonnegative_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ingestion_jobs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="ingestion_idempotency_per_organization"
        ),
        sa.UniqueConstraint(
            "organization_id", "source", "sha256", name="ingestion_content_per_source"
        ),
    )
    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ingestion_jobs_org_status_created",
            ["organization_id", "status", "created_at"],
            unique=False,
        )

    op.create_table(
        "roles",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("family", sa.String(length=160), nullable=True),
        sa.Column("is_unknown", sa.Boolean(), nullable=False),
        sa.Column(
            "attributes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_roles_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("organization_id", "code", name="role_code_per_organization"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index("ix_roles_org_family", ["organization_id", "family"], unique=False)

    op.create_table(
        "users",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("external_user_id", sa.String(length=160), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                name="user_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("first_seen", sa.Date(), nullable=True),
        sa.Column("last_seen", sa.Date(), nullable=True),
        sa.Column(
            "attributes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "organization_id", "external_user_id", name="user_external_id_per_organization"
        ),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_org_status", ["organization_id", "status"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("ingestion_job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "canonical_events",
                "features",
                "sequences",
                "role_context",
                "branch_scores",
                "reference_profile",
                "risk_assessments",
                "model",
                "manifest",
                name="artifact_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "staged",
                "ready",
                "invalid",
                "archived",
                name="artifact_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("uri", sa.String(length=1024), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=100), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("min_date", sa.Date(), nullable=True),
        sa.Column("max_date", sa.Date(), nullable=True),
        sa.Column(
            "manifest_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("row_count >= 0", name=op.f("ck_artifacts_artifact_nonnegative_rows")),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifacts_artifact_nonnegative_size")),
        sa.ForeignKeyConstraint(
            ["ingestion_job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_artifacts_ingestion_job_id_ingestion_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_artifacts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("organization_id", "kind", "uri", name="artifact_uri_per_kind"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_artifacts_org_kind_status", ["organization_id", "kind", "status"], unique=False
        )

    op.create_table(
        "canonical_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("event_uid", sa.String(length=160), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "logon",
                "device",
                "file",
                "http",
                "email",
                name="event_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("original_id", sa.String(length=240), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("pc", sa.String(length=240), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("object_ref", sa.Text(), nullable=True),
        sa.Column(
            "pc_context",
            sa.Enum(
                "own",
                "shared",
                "foreign",
                "unknown",
                name="pc_context",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "time_context",
            sa.Enum(
                "work",
                "after",
                "weekend",
                name="time_context",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("ingestion_job_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "row_number IS NULL OR row_number > 0",
            name=op.f("ck_canonical_events_event_positive_row_number"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_canonical_events_ingestion_job_id_ingestion_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_canonical_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_canonical_events_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_events")),
        sa.UniqueConstraint("organization_id", "event_uid", name="canonical_event_uid_per_org"),
        sa.UniqueConstraint(
            "organization_id", "source", "original_id", name="canonical_original_event_per_source"
        ),
    )
    with op.batch_alter_table("canonical_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_canonical_events_org_source_day",
            ["organization_id", "source", "event_date"],
            unique=False,
        )
        batch_op.create_index(
            "ix_canonical_events_org_user_day_ts",
            ["organization_id", "user_id", "event_date", "event_timestamp"],
            unique=False,
        )

    op.create_table(
        "ingestion_checkpoints",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("partition_key", sa.String(length=240), nullable=False),
        sa.Column("row_offset", sa.Integer(), nullable=False),
        sa.Column(
            "cursor_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("input_checksum", sa.String(length=128), nullable=True),
        sa.Column("output_checksum", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "row_offset >= 0", name=op.f("ck_ingestion_checkpoints_checkpoint_nonnegative_offset")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_ingestion_checkpoints_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_checkpoints")),
        sa.UniqueConstraint("job_id", "partition_key", name="checkpoint_partition_per_job"),
    )
    op.create_table(
        "role_assignments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_snapshot_date", sa.Date(), nullable=True),
        sa.Column("source_snapshot", sa.String(length=300), nullable=True),
        sa.Column("source_checksum", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_snapshot_date IS NULL OR source_snapshot_date <= valid_from",
            name=op.f("ck_role_assignments_role_snapshot_not_future"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_role_assignments_role_assignment_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_assignments_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_role_assignments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        sa.UniqueConstraint("user_id", "valid_from", name="role_assignment_start_per_user"),
    )
    with op.batch_alter_table("role_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_role_assignments_user_range", ["user_id", "valid_from", "valid_to"], unique=False
        )

    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
        op.execute(
            """
            ALTER TABLE role_assignments
            ADD CONSTRAINT role_assignments_user_validity_no_overlap
            EXCLUDE USING gist (
                user_id WITH =,
                daterange(
                    valid_from,
                    coalesce(valid_to, 'infinity'::date),
                    '[)'
                ) WITH &&
            )
            """
        )

    op.create_table(
        "reference_profiles",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "branch",
            sa.Enum(
                "feature",
                "sequence",
                name="reference_branch",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum(
                "person",
                "role",
                "global",
                name="reference_level",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("scope_key", sa.String(length=160), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("role_id", sa.Uuid(), nullable=True),
        sa.Column("role_assignment_id", sa.Uuid(), nullable=True),
        sa.Column("model_version", sa.String(length=120), nullable=False),
        sa.Column("config_version", sa.String(length=120), nullable=False),
        sa.Column("catalog_version", sa.String(length=120), nullable=False),
        sa.Column("fitted_from", sa.Date(), nullable=True),
        sa.Column("fitted_through", sa.Date(), nullable=False),
        sa.Column("support_days", sa.Integer(), nullable=False),
        sa.Column("support_users", sa.Integer(), nullable=False),
        sa.Column("support_transitions", sa.Integer(), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=True),
        sa.Column(
            "support_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "statistics_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "calibrator_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "coverage IS NULL OR (coverage >= 0 AND coverage <= 1)",
            name=op.f("ck_reference_profiles_reference_coverage_range"),
        ),
        sa.CheckConstraint(
            "support_days >= 0",
            name=op.f("ck_reference_profiles_reference_support_days_nonnegative"),
        ),
        sa.CheckConstraint(
            "support_transitions >= 0",
            name=op.f("ck_reference_profiles_reference_support_transitions_nonnegative"),
        ),
        sa.CheckConstraint(
            "support_users >= 0",
            name=op.f("ck_reference_profiles_reference_support_users_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_reference_profiles_artifact_id_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reference_profiles_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["role_assignments.id"],
            name=op.f("fk_reference_profiles_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_reference_profiles_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reference_profiles_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_profiles")),
        sa.UniqueConstraint(
            "organization_id",
            "branch",
            "level",
            "scope_key",
            "model_version",
            "config_version",
            "fitted_through",
            name="reference_release_per_scope",
        ),
    )
    op.create_table(
        "user_day_features",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("role_assignment_id", sa.Uuid(), nullable=True),
        sa.Column("catalog_id", sa.Uuid(), nullable=False),
        sa.Column(
            "split",
            sa.Enum(
                "train",
                "validation",
                "test",
                "production",
                name="feature_data_split",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "present_mask",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("feature_count", sa.Integer(), nullable=False),
        sa.Column("is_observed_day", sa.Boolean(), nullable=False),
        sa.Column("is_active_day", sa.Boolean(), nullable=False),
        sa.Column(
            "context_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("input_checksum", sa.String(length=128), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "feature_count > 0", name=op.f("ck_user_day_features_feature_positive_count")
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_user_day_features_artifact_id_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["feature_catalogs.id"],
            name=op.f("fk_user_day_features_catalog_id_feature_catalogs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_user_day_features_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["role_assignments.id"],
            name=op.f("fk_user_day_features_role_assignment_id_role_assignments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_day_features_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_day_features")),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "day",
            "catalog_id",
            name="feature_vector_per_user_day_catalog",
        ),
    )
    with op.batch_alter_table("user_day_features", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_day_features_org_day", ["organization_id", "day"], unique=False
        )

    op.create_table(
        "user_day_sequences",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("role_assignment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "split",
            sa.Enum(
                "train",
                "validation",
                "test",
                "production",
                name="sequence_data_split",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("vocabulary_version", sa.String(length=80), nullable=False),
        sa.Column(
            "tokens",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "pc_contexts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "time_contexts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "gap_buckets",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "event_uids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "side_fields",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("seq_len", sa.Integer(), nullable=False),
        sa.Column("stored_len", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("input_checksum", sa.String(length=128), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "seq_len >= 0", name=op.f("ck_user_day_sequences_sequence_nonnegative_length")
        ),
        sa.CheckConstraint(
            "stored_len >= 0 AND stored_len <= 256",
            name=op.f("ck_user_day_sequences_sequence_stored_length_range"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_user_day_sequences_artifact_id_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_user_day_sequences_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["role_assignments.id"],
            name=op.f("fk_user_day_sequences_role_assignment_id_role_assignments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_day_sequences_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_day_sequences")),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "day",
            "vocabulary_version",
            name="sequence_per_user_day_vocabulary",
        ),
    )
    with op.batch_alter_table("user_day_sequences", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_day_sequences_org_day", ["organization_id", "day"], unique=False
        )

    op.create_table(
        "branch_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("role_assignment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "branch",
            sa.Enum(
                "feature",
                "sequence",
                name="score_branch",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "scored",
                "no_score",
                name="score_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "selected_level",
            sa.Enum(
                "person",
                "role",
                "global",
                name="score_reference_level",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("reference_profile_id", sa.Uuid(), nullable=True),
        sa.Column("raw_score", sa.Float(), nullable=True),
        sa.Column("calibrated_score", sa.Float(), nullable=True),
        sa.Column(
            "support_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "fallback_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=120), nullable=False),
        sa.Column("config_version", sa.String(length=120), nullable=False),
        sa.Column("scoring_run_id", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'no_score' AND selected_level IS NULL AND reference_profile_id IS NULL AND raw_score IS NULL AND calibrated_score IS NULL) OR (status = 'scored' AND selected_level IS NOT NULL AND raw_score IS NOT NULL AND calibrated_score IS NOT NULL)",
            name=op.f("ck_branch_scores_branch_score_status_shape"),
        ),
        sa.CheckConstraint(
            "calibrated_score IS NULL OR (calibrated_score >= 0 AND calibrated_score <= 1)",
            name=op.f("ck_branch_scores_branch_calibrated_range"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_branch_scores_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reference_profile_id"],
            ["reference_profiles.id"],
            name=op.f("fk_branch_scores_reference_profile_id_reference_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["role_assignments.id"],
            name=op.f("fk_branch_scores_role_assignment_id_role_assignments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_branch_scores_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branch_scores")),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "day",
            "branch",
            "model_version",
            "config_version",
            name="branch_score_release_per_user_day",
        ),
    )
    with op.batch_alter_table("branch_scores", schema=None) as batch_op:
        batch_op.create_index("ix_branch_scores_user_day", ["user_id", "day"], unique=False)

    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("role_assignment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "split",
            sa.Enum(
                "train",
                "validation",
                "test",
                "production",
                name="assessment_data_split",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "scored",
                "no_score",
                name="assessment_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("feature_score_id", sa.Uuid(), nullable=True),
        sa.Column("sequence_score_id", sa.Uuid(), nullable=True),
        sa.Column("feature_weight", sa.Float(), nullable=False),
        sa.Column("sequence_weight", sa.Float(), nullable=False),
        sa.Column("risk", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("is_alert", sa.Boolean(), nullable=False),
        sa.Column("model_version", sa.String(length=120), nullable=False),
        sa.Column("config_version", sa.String(length=120), nullable=False),
        sa.Column("scoring_run_id", sa.String(length=160), nullable=False),
        sa.Column(
            "fusion_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'no_score' AND feature_score_id IS NULL AND sequence_score_id IS NULL AND feature_weight = 0 AND sequence_weight = 0 AND risk IS NULL AND threshold IS NULL AND is_alert = false) OR (status = 'scored' AND (feature_score_id IS NOT NULL OR sequence_score_id IS NOT NULL) AND risk IS NOT NULL AND threshold IS NOT NULL)",
            name=op.f("ck_risk_assessments_risk_status_shape"),
        ),
        sa.CheckConstraint(
            "status = 'no_score' OR (feature_weight + sequence_weight >= 0.999999 AND feature_weight + sequence_weight <= 1.000001)",
            name=op.f("ck_risk_assessments_risk_weights_sum"),
        ),
        sa.CheckConstraint(
            "status = 'no_score' OR (is_alert = true AND risk >= threshold) OR (is_alert = false AND risk < threshold)",
            name=op.f("ck_risk_assessments_risk_alert_matches_threshold"),
        ),
        sa.CheckConstraint(
            "risk IS NULL OR (risk >= 0 AND risk <= 1)",
            name=op.f("ck_risk_assessments_risk_value_range"),
        ),
        sa.CheckConstraint(
            "threshold IS NULL OR (threshold >= 0 AND threshold <= 1)",
            name=op.f("ck_risk_assessments_risk_threshold_range"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_score_id"],
            ["branch_scores.id"],
            name=op.f("fk_risk_assessments_feature_score_id_branch_scores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_risk_assessments_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["role_assignments.id"],
            name=op.f("fk_risk_assessments_role_assignment_id_role_assignments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sequence_score_id"],
            ["branch_scores.id"],
            name=op.f("fk_risk_assessments_sequence_score_id_branch_scores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_risk_assessments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_assessments")),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "day",
            "model_version",
            "config_version",
            name="risk_release_per_user_day",
        ),
    )
    with op.batch_alter_table("risk_assessments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_risk_assessments_org_day_alert",
            ["organization_id", "day", "is_alert"],
            unique=False,
        )

    op.create_table(
        "alerts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "acknowledged",
                "in_review",
                "investigating",
                "resolved",
                "closed",
                "dismissed",
                "false_positive",
                name="alert_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="alert_severity",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("assignee", sa.String(length=240), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "notes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["risk_assessments.id"],
            name=op.f("fk_alerts_assessment_id_risk_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_alerts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("assessment_id", name="alert_per_assessment"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alerts_org_status_opened", ["organization_id", "status", "opened_at"], unique=False
        )

    op.create_table(
        "safe_update_candidates",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_assignment_id", sa.Uuid(), nullable=False),
        sa.Column("reference_profile_id", sa.Uuid(), nullable=False),
        sa.Column("source_assessment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "branch",
            sa.Enum(
                "feature",
                "sequence",
                name="safe_update_branch",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("candidate_day", sa.Date(), nullable=False),
        sa.Column("quarantine_until", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "accepted",
                "rejected",
                "applied",
                name="safe_update_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "reason_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("influence_cap", sa.Float(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("before_checksum", sa.String(length=128), nullable=True),
        sa.Column("after_checksum", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "influence_cap >= 0 AND influence_cap <= 1",
            name=op.f("ck_safe_update_candidates_safe_update_influence_cap_range"),
        ),
        sa.CheckConstraint(
            "quarantine_until >= candidate_day",
            name=op.f("ck_safe_update_candidates_safe_update_quarantine_after_day"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_safe_update_candidates_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reference_profile_id"],
            ["reference_profiles.id"],
            name=op.f("fk_safe_update_candidates_reference_profile_id_reference_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["role_assignments.id"],
            name=op.f("fk_safe_update_candidates_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_assessment_id"],
            ["risk_assessments.id"],
            name=op.f("fk_safe_update_candidates_source_assessment_id_risk_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_safe_update_candidates_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safe_update_candidates")),
        sa.UniqueConstraint(
            "reference_profile_id",
            "branch",
            "candidate_day",
            name="safe_update_day_per_profile_branch",
        ),
    )
    with op.batch_alter_table("safe_update_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_safe_update_candidates_status_quarantine",
            ["status", "quarantine_until"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("safe_update_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_safe_update_candidates_status_quarantine")

    op.drop_table("safe_update_candidates")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_org_status_opened")

    op.drop_table("alerts")
    with op.batch_alter_table("risk_assessments", schema=None) as batch_op:
        batch_op.drop_index("ix_risk_assessments_org_day_alert")

    op.drop_table("risk_assessments")
    with op.batch_alter_table("branch_scores", schema=None) as batch_op:
        batch_op.drop_index("ix_branch_scores_user_day")

    op.drop_table("branch_scores")
    with op.batch_alter_table("user_day_sequences", schema=None) as batch_op:
        batch_op.drop_index("ix_user_day_sequences_org_day")

    op.drop_table("user_day_sequences")
    with op.batch_alter_table("user_day_features", schema=None) as batch_op:
        batch_op.drop_index("ix_user_day_features_org_day")

    op.drop_table("user_day_features")
    op.drop_table("reference_profiles")
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            ALTER TABLE role_assignments
            DROP CONSTRAINT role_assignments_user_validity_no_overlap
            """
        )

    with op.batch_alter_table("role_assignments", schema=None) as batch_op:
        batch_op.drop_index("ix_role_assignments_user_range")

    op.drop_table("role_assignments")
    op.drop_table("ingestion_checkpoints")
    with op.batch_alter_table("canonical_events", schema=None) as batch_op:
        batch_op.drop_index("ix_canonical_events_org_user_day_ts")
        batch_op.drop_index("ix_canonical_events_org_source_day")

    op.drop_table("canonical_events")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index("ix_artifacts_org_kind_status")

    op.drop_table("artifacts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_org_status")

    op.drop_table("users")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index("ix_roles_org_family")

    op.drop_table("roles")
    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_ingestion_jobs_org_status_created")

    op.drop_table("ingestion_jobs")
    op.drop_table("feature_definitions")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_request")
        batch_op.drop_index("ix_audit_logs_entity_time")

    op.drop_table("audit_logs")
    op.drop_table("organizations")
    op.drop_table("feature_catalogs")
    # ### end Alembic commands ###
